# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_norm <- function(a) {
    .Call('_TrecFastTest_Rcpp_norm', PACKAGE = 'TrecFastTest', a)
}

Rcpp_logSumExp <- function(log_x) {
    .Call('_TrecFastTest_Rcpp_logSumExp', PACKAGE = 'TrecFastTest', log_x)
}

Rcpp_min_diff <- function(x) {
    .Call('_TrecFastTest_Rcpp_min_diff', PACKAGE = 'TrecFastTest', x)
}

Rcpp_lgy_add_1 <- function(y) {
    .Call('_TrecFastTest_Rcpp_lgy_add_1', PACKAGE = 'TrecFastTest', y)
}

compute_offset <- function(bxj, z, offsets) {
    invisible(.Call('_TrecFastTest_compute_offset', PACKAGE = 'TrecFastTest', bxj, z, offsets))
}

Rcpp_loglikNB <- function(phi, mu1, y, lgy1) {
    .Call('_TrecFastTest_Rcpp_loglikNB', PACKAGE = 'TrecFastTest', phi, mu1, y, lgy1)
}

Rcpp_loglikNB_bxj <- function(phi, mu1, y, lgy1) {
    .Call('_TrecFastTest_Rcpp_loglikNB_bxj', PACKAGE = 'TrecFastTest', phi, mu1, y, lgy1)
}

Rcpp_loglik_pois <- function(mu1, y, lgy1) {
    .Call('_TrecFastTest_Rcpp_loglik_pois', PACKAGE = 'TrecFastTest', mu1, y, lgy1)
}

Rcpp_logLTReC <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu) {
    .Call('_TrecFastTest_Rcpp_logLTReC', PACKAGE = 'TrecFastTest', bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu)
}

Rcpp_logLTReC_bxj <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu) {
    .Call('_TrecFastTest_Rcpp_logLTReC_bxj', PACKAGE = 'TrecFastTest', bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu)
}

Rcpp_trec_grad_bxj <- function(bxj, y, z, mu, phi, fam_nb) {
    .Call('_TrecFastTest_Rcpp_trec_grad_bxj', PACKAGE = 'TrecFastTest', bxj, y, z, mu, phi, fam_nb)
}

Rcpp_trec_bxj_BFGS <- function(bxj0, y, X, z, BETA, phi, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_trec_bxj_BFGS', PACKAGE = 'TrecFastTest', bxj0, y, X, z, BETA, phi, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_NB_reg_LL <- function(y, X, offsets, PARAMS, lgy1, mu) {
    .Call('_TrecFastTest_Rcpp_NB_reg_LL', PACKAGE = 'TrecFastTest', y, X, offsets, PARAMS, lgy1, mu)
}

Rcpp_NB_reg_grad <- function(y, X, mu, PARAMS) {
    .Call('_TrecFastTest_Rcpp_NB_reg_grad', PACKAGE = 'TrecFastTest', y, X, mu, PARAMS)
}

Rcpp_NB_reg_Hess <- function(y, X, mu, PARAMS) {
    .Call('_TrecFastTest_Rcpp_NB_reg_Hess', PACKAGE = 'TrecFastTest', y, X, mu, PARAMS)
}

Rcpp_pois_reg_LL <- function(y, X, offsets, PARAMS, lgy1, mu) {
    .Call('_TrecFastTest_Rcpp_pois_reg_LL', PACKAGE = 'TrecFastTest', y, X, offsets, PARAMS, lgy1, mu)
}

Rcpp_pois_reg_grad <- function(y, X, mu, PARAMS) {
    .Call('_TrecFastTest_Rcpp_pois_reg_grad', PACKAGE = 'TrecFastTest', y, X, mu, PARAMS)
}

Rcpp_pois_reg_Hess <- function(y, X, mu, PARAMS) {
    .Call('_TrecFastTest_Rcpp_pois_reg_Hess', PACKAGE = 'TrecFastTest', y, X, mu, PARAMS)
}

Rcpp_reg_LL <- function(y, X, offsets, PARAMS, fam_nb, lgy1, mu) {
    .Call('_TrecFastTest_Rcpp_reg_LL', PACKAGE = 'TrecFastTest', y, X, offsets, PARAMS, fam_nb, lgy1, mu)
}

Rcpp_reg_grad <- function(y, X, mu, PARAMS, fam_nb) {
    .Call('_TrecFastTest_Rcpp_reg_grad', PACKAGE = 'TrecFastTest', y, X, mu, PARAMS, fam_nb)
}

Rcpp_reg_Hess <- function(y, X, mu, PARAMS, fam_nb) {
    .Call('_TrecFastTest_Rcpp_reg_Hess', PACKAGE = 'TrecFastTest', y, X, mu, PARAMS, fam_nb)
}

Rcpp_reg <- function(y, X, offsets, params0, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_reg', PACKAGE = 'TrecFastTest', y, X, offsets, params0, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_reg_BFGS <- function(y, X, offsets, params0, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_reg_BFGS', PACKAGE = 'TrecFastTest', y, X, offsets, params0, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_trec <- function(y, X, z, fam_nb, lgy1, ini_bxj = 0.0, LL_null = 0.0, ini_reg_par = NULL, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call('_TrecFastTest_Rcpp_trec', PACKAGE = 'TrecFastTest', y, X, z, fam_nb, lgy1, ini_bxj, LL_null, ini_reg_par, max_iter, eps, show)
}

Rcpp_loglikBB <- function(ni, ni0, Pi1, log_theta, lbc, zeta) {
    .Call('_TrecFastTest_Rcpp_loglikBB', PACKAGE = 'TrecFastTest', ni, ni0, Pi1, log_theta, lbc, zeta)
}

Rcpp_ase_grad <- function(ni, ni0, Pi1, log_theta, zeta) {
    .Call('_TrecFastTest_Rcpp_ase_grad', PACKAGE = 'TrecFastTest', ni, ni0, Pi1, log_theta, zeta)
}

Rcpp_ase_grad_Pi <- function(ni, ni0, Pi1, log_theta, zeta) {
    .Call('_TrecFastTest_Rcpp_ase_grad_Pi', PACKAGE = 'TrecFastTest', ni, ni0, Pi1, log_theta, zeta)
}

Rcpp_ase_grad_H0 <- function(ni, ni0, Pi1, log_theta, zeta) {
    .Call('_TrecFastTest_Rcpp_ase_grad_H0', PACKAGE = 'TrecFastTest', ni, ni0, Pi1, log_theta, zeta)
}

Rcpp_ase_BFGS <- function(ni, ni0, zeta, params0, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_ase_BFGS', PACKAGE = 'TrecFastTest', ni, ni0, zeta, params0, lbc, max_iter, eps, show)
}

Rcpp_ase_theta_BFGS <- function(ni, ni0, zeta, Pi1, lg_theta, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_ase_theta_BFGS', PACKAGE = 'TrecFastTest', ni, ni0, zeta, Pi1, lg_theta, lbc, max_iter, eps, show)
}

Rcpp_ase_theta_BFGS2 <- function(ni, ni0, zeta, Pi1, lg_theta, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_ase_theta_BFGS2', PACKAGE = 'TrecFastTest', ni, ni0, zeta, Pi1, lg_theta, lbc, max_iter, eps, show)
}

Rcpp_ase <- function(ni, ni0, zeta, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_ase', PACKAGE = 'TrecFastTest', ni, ni0, zeta, lbc, max_iter, eps, show)
}

Rcpp_trecase_LL <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta) {
    .Call('_TrecFastTest_Rcpp_trecase_LL', PACKAGE = 'TrecFastTest', bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta)
}

Rcpp_trecase_grad_bxj <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta) {
    .Call('_TrecFastTest_Rcpp_trecase_grad_bxj', PACKAGE = 'TrecFastTest', bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta)
}

Rcpp_trecase_BFGS <- function(bxj0, y, X, z, BETA, phi, fam_nb, lgy1, ni, ni0, log_theta, lbc, zeta, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call('_TrecFastTest_Rcpp_trecase_BFGS', PACKAGE = 'TrecFastTest', bxj0, y, X, z, BETA, phi, fam_nb, lgy1, ni, ni0, log_theta, lbc, zeta, max_iter, eps, show)
}

Rcpp_trecase <- function(y, X, z, fam_nb, lgy1, ni, ni0, zeta, lbc, ini_bxj = 0.0, LL_null = 0.0, ini_reg_par = NULL, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call('_TrecFastTest_Rcpp_trecase', PACKAGE = 'TrecFastTest', y, X, z, fam_nb, lgy1, ni, ni0, zeta, lbc, ini_bxj, LL_null, ini_reg_par, max_iter, eps, show)
}

Rcpp_trecase_mtest <- function(Y, Y1, Y2, Z, XX, SNP_pos, sChr, fam_nb, gene_start, gene_end, gChr, file_trec = "trec.txt", file_trecase = "trecase.txt", cis_widow = 1e5, useASE = 1L, min_ASE_total = 8L, min_nASE = 10L, eps = 1e-5, max_iter = 4000L, show = FALSE) {
    invisible(.Call('_TrecFastTest_Rcpp_trecase_mtest', PACKAGE = 'TrecFastTest', Y, Y1, Y2, Z, XX, SNP_pos, sChr, fam_nb, gene_start, gene_end, gChr, file_trec, file_trecase, cis_widow, useASE, min_ASE_total, min_nASE, eps, max_iter, show))
}

