# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_offset <- function(bxj, z, offsets) {
    invisible(.Call(`_asSeq2_compute_offset`, bxj, z, offsets))
}

Rcpp_loglikNB_bxj <- function(phi, mu1, y, lgy1) {
    .Call(`_asSeq2_Rcpp_loglikNB_bxj`, phi, mu1, y, lgy1)
}

Rcpp_loglik_pois <- function(mu1, y, lgy1) {
    .Call(`_asSeq2_Rcpp_loglik_pois`, mu1, y, lgy1)
}

Rcpp_logLTReC <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu) {
    .Call(`_asSeq2_Rcpp_logLTReC`, bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu)
}

Rcpp_logLTReC_bxj <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu) {
    .Call(`_asSeq2_Rcpp_logLTReC_bxj`, bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu)
}

Rcpp_grad_hess_bxj_trec <- function(bxj, y, z, mu, phi, fam_nb) {
    .Call(`_asSeq2_Rcpp_grad_hess_bxj_trec`, bxj, y, z, mu, phi, fam_nb)
}

Rcpp_trec_grad_bxj <- function(bxj, y, z, mu, phi, fam_nb) {
    .Call(`_asSeq2_Rcpp_trec_grad_bxj`, bxj, y, z, mu, phi, fam_nb)
}

Rcpp_trec_bxj_BFGS <- function(bxj0, y, X, z, BETA, phi, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_trec_bxj_BFGS`, bxj0, y, X, z, BETA, phi, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_trec_bxj <- function(y, X, bxj, z, BETA, phi, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_trec_bxj`, y, X, bxj, z, BETA, phi, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_NB_reg_LL <- function(y, X, offsets, PARAMS, lgy1, mu) {
    .Call(`_asSeq2_Rcpp_NB_reg_LL`, y, X, offsets, PARAMS, lgy1, mu)
}

Rcpp_NB_reg_grad <- function(y, X, mu, PARAMS) {
    .Call(`_asSeq2_Rcpp_NB_reg_grad`, y, X, mu, PARAMS)
}

Rcpp_NB_reg_Hess <- function(y, X, mu, PARAMS) {
    .Call(`_asSeq2_Rcpp_NB_reg_Hess`, y, X, mu, PARAMS)
}

Rcpp_pois_reg_LL <- function(y, X, offsets, PARAMS, lgy1, mu) {
    .Call(`_asSeq2_Rcpp_pois_reg_LL`, y, X, offsets, PARAMS, lgy1, mu)
}

Rcpp_pois_reg_grad <- function(y, X, mu, PARAMS) {
    .Call(`_asSeq2_Rcpp_pois_reg_grad`, y, X, mu, PARAMS)
}

Rcpp_pois_reg_Hess <- function(y, X, mu, PARAMS) {
    .Call(`_asSeq2_Rcpp_pois_reg_Hess`, y, X, mu, PARAMS)
}

Rcpp_reg_LL <- function(y, X, offsets, PARAMS, fam_nb, lgy1, mu) {
    .Call(`_asSeq2_Rcpp_reg_LL`, y, X, offsets, PARAMS, fam_nb, lgy1, mu)
}

Rcpp_reg_grad <- function(y, X, mu, PARAMS, fam_nb) {
    .Call(`_asSeq2_Rcpp_reg_grad`, y, X, mu, PARAMS, fam_nb)
}

Rcpp_reg_Hess <- function(y, X, mu, PARAMS, fam_nb) {
    .Call(`_asSeq2_Rcpp_reg_Hess`, y, X, mu, PARAMS, fam_nb)
}

Rcpp_reg <- function(y, X, offsets, params0, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_reg`, y, X, offsets, params0, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_reg_BFGS <- function(y, X, offsets, params0, fam_nb, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_reg_BFGS`, y, X, offsets, params0, fam_nb, lgy1, max_iter, eps, show)
}

Rcpp_trec <- function(y, X, z, fam_nb, lgy1, ini_bxj = 0.0, LL_null = 0.0, ini_reg_par = NULL, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_Rcpp_trec`, y, X, z, fam_nb, lgy1, ini_bxj, LL_null, ini_reg_par, max_iter, eps, show)
}

Rcpp_loglikBB <- function(ni, ni0, bxj, log_theta, lbc, zeta) {
    .Call(`_asSeq2_Rcpp_loglikBB`, ni, ni0, bxj, log_theta, lbc, zeta)
}

Rcpp_loglikBB_Pi <- function(ni, ni0, bxj, log_theta, lbc, zeta) {
    .Call(`_asSeq2_Rcpp_loglikBB_Pi`, ni, ni0, bxj, log_theta, lbc, zeta)
}

Rcpp_ase_grad <- function(ni, ni0, bxj, log_theta, zeta) {
    .Call(`_asSeq2_Rcpp_ase_grad`, ni, ni0, bxj, log_theta, zeta)
}

Rcpp_ase_grad_Pi <- function(ni, ni0, bxj, log_theta, zeta) {
    .Call(`_asSeq2_Rcpp_ase_grad_Pi`, ni, ni0, bxj, log_theta, zeta)
}

Rcpp_ase_grad_H0 <- function(ni, ni0, bxj, log_theta, zeta) {
    .Call(`_asSeq2_Rcpp_ase_grad_H0`, ni, ni0, bxj, log_theta, zeta)
}

Rcpp_ase_Pi_BFGS <- function(ni, ni0, zeta, bxj, lg_theta, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_ase_Pi_BFGS`, ni, ni0, zeta, bxj, lg_theta, lbc, max_iter, eps, show)
}

Rcpp_ase_BFGS <- function(ni, ni0, zeta, params0, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_ase_BFGS`, ni, ni0, zeta, params0, lbc, max_iter, eps, show)
}

Rcpp_ase_theta_BFGS <- function(ni, ni0, zeta, bxj, lg_theta, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_ase_theta_BFGS`, ni, ni0, zeta, bxj, lg_theta, lbc, max_iter, eps, show)
}

Rcpp_ase <- function(ni, ni0, zeta, lbc, theta0 = 0.0, LL_null_ase = 0.0, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_ase`, ni, ni0, zeta, lbc, theta0, LL_null_ase, max_iter, eps, show)
}

Rcpp_trecase_LL <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta) {
    .Call(`_asSeq2_Rcpp_trecase_LL`, bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta)
}

Rcpp_trecase_grad_bxj <- function(bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta) {
    .Call(`_asSeq2_Rcpp_trecase_grad_bxj`, bxj, y, X, z, BETA, phi, fam_nb, lgy1, mu, ni, ni0, log_theta, lbc, zeta)
}

Rcpp_trecase_BFGS <- function(bxj0, y, X, z, BETA, phi, fam_nb, lgy1, ni, ni0, log_theta, lbc, zeta, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_Rcpp_trecase_BFGS`, bxj0, y, X, z, BETA, phi, fam_nb, lgy1, ni, ni0, log_theta, lbc, zeta, max_iter, eps, show)
}

Rcpp_trecase <- function(y, X, z, fam_nb, lgy1, ni, ni0, zeta, lbc, ini_bxj = 0.0, LL_null = 0.0, ini_reg_par = NULL, theta0 = 0.0, LL_null_ase = 0.0, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_Rcpp_trecase`, y, X, z, fam_nb, lgy1, ni, ni0, zeta, lbc, ini_bxj, LL_null, ini_reg_par, theta0, LL_null_ase, max_iter, eps, show)
}

Rcpp_ase_mtest <- function(Y1, Y2, Z, SNP_pos, sChr, gene_start, gene_end, gChr, file_ase = "ase.txt", cis_window = 1e5, min_ASE_total = 8L, min_nASE = 5L, min_nASE_het = 5L, eps = 1e-5, max_iter = 4000L, show = FALSE) {
    invisible(.Call(`_asSeq2_Rcpp_ase_mtest`, Y1, Y2, Z, SNP_pos, sChr, gene_start, gene_end, gChr, file_ase, cis_window, min_ASE_total, min_nASE, min_nASE_het, eps, max_iter, show))
}

Rcpp_trecase_mtest <- function(Y, Y1, Y2, Z, XX, SNP_pos, sChr, fam_nb, gene_start, gene_end, gChr, GeneSnpList, file_trec = "trec.txt", file_trecase = "trecase.txt", transTestP = 0.01, cis_window = 1e5, useASE = 1L, min_ASE_total = 8L, min_nASE = 5L, min_nASE_het = 5L, eps = 1e-5, max_iter = 4000L, show = FALSE) {
    invisible(.Call(`_asSeq2_Rcpp_trecase_mtest`, Y, Y1, Y2, Z, XX, SNP_pos, sChr, fam_nb, gene_start, gene_end, gChr, GeneSnpList, file_trec, file_trecase, transTestP, cis_window, useASE, min_ASE_total, min_nASE, min_nASE_het, eps, max_iter, show))
}

Rcpp_norm <- function(a) {
    .Call(`_asSeq2_Rcpp_norm`, a)
}

Rcpp_logSumExp <- function(log_x) {
    .Call(`_asSeq2_Rcpp_logSumExp`, log_x)
}

Rcpp_min_diff <- function(x) {
    .Call(`_asSeq2_Rcpp_min_diff`, x)
}

Rcpp_lgy_add_1 <- function(y) {
    .Call(`_asSeq2_Rcpp_lgy_add_1`, y)
}

Rcpp_loglikNB <- function(y, phi, lgy1, mu) {
    .Call(`_asSeq2_Rcpp_loglikNB`, y, phi, lgy1, mu)
}

RcppT_compute_offset <- function(z, RHO, KAPPA, ETA, GAMMA, tau1, tau2, offsets) {
    invisible(.Call(`_asSeq2_RcppT_compute_offset`, z, RHO, KAPPA, ETA, GAMMA, tau1, tau2, offsets))
}

RcppT_compute_expXbeta <- function(X, BETA, expXbeta) {
    invisible(.Call(`_asSeq2_RcppT_compute_expXbeta`, X, BETA, expXbeta))
}

RcppT_reg_LL <- function(y, X, offsets, PARAMS, lgy1, mu) {
    .Call(`_asSeq2_RcppT_reg_LL`, y, X, offsets, PARAMS, lgy1, mu)
}

RcppT_reg_grad <- function(y, X, mu, PARAMS) {
    .Call(`_asSeq2_RcppT_reg_grad`, y, X, mu, PARAMS)
}

RcppT_reg_BFGS <- function(y, X, offsets, params0, lgy1, max_iter, eps, show) {
    .Call(`_asSeq2_RcppT_reg_BFGS`, y, X, offsets, params0, lgy1, max_iter, eps, show)
}

RcppT_loglikNB_KEG <- function(para, H0, y, z, phi, RHO, tau1, tau2, lgy1, expXbeta, offsets, mu) {
    .Call(`_asSeq2_RcppT_loglikNB_KEG`, para, H0, y, z, phi, RHO, tau1, tau2, lgy1, expXbeta, offsets, mu)
}

RcppT_grad_NB <- function(para, H0, y, z, RHO, phi, tau1, tau2, expXbeta, offsets, mu) {
    .Call(`_asSeq2_RcppT_grad_NB`, para, H0, y, z, RHO, phi, tau1, tau2, expXbeta, offsets, mu)
}

RcppT_trec_KEG_BFGS <- function(para0, H0, y, z, RHO, X, BETA, phi, tau1, tau2, lgy1, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_RcppT_trec_KEG_BFGS`, para0, H0, y, z, RHO, X, BETA, phi, tau1, tau2, lgy1, max_iter, eps, show)
}

RcppT_trec_sfit <- function(H0, para0, y, z, RHO, X, tau1, tau2, lgy1, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_trec_sfit`, H0, para0, y, z, RHO, X, tau1, tau2, lgy1, max_iter, eps, show)
}

RcppT_trec <- function(y, z, RHO, X, tau1, tau2, lgy1, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_trec`, y, z, RHO, X, tau1, tau2, lgy1, max_iter, eps, show)
}

RcppT_compite_pi <- function(z_AS, RHO_AS, KAPPA, ETA, GAMMA, tauB, tau, pis) {
    invisible(.Call(`_asSeq2_RcppT_compite_pi`, z_AS, RHO_AS, KAPPA, ETA, GAMMA, tauB, tau, pis))
}

RcppT_loglikBB_KEG <- function(para, H0, z_AS, RHO_AS, ni, ni0, log_theta, lbc, tauB, tau, pis) {
    .Call(`_asSeq2_RcppT_loglikBB_KEG`, para, H0, z_AS, RHO_AS, ni, ni0, log_theta, lbc, tauB, tau, pis)
}

RcppT_grad_BB_KEG <- function(para, H0, z_AS, RHO_AS, ni, ni0, log_theta, lbc, tauB, tau, pis) {
    .Call(`_asSeq2_RcppT_grad_BB_KEG`, para, H0, z_AS, RHO_AS, ni, ni0, log_theta, lbc, tauB, tau, pis)
}

RcppT_loglikBB_THETA <- function(ni, ni0, log_theta, pis, lbc) {
    .Call(`_asSeq2_RcppT_loglikBB_THETA`, ni, ni0, log_theta, pis, lbc)
}

RcppT_grad_BB_THETA <- function(ni, ni0, log_theta, pis) {
    .Call(`_asSeq2_RcppT_grad_BB_THETA`, ni, ni0, log_theta, pis)
}

RcppT_ase_theta_BFGS <- function(lg_theta, ni, ni0, pis, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_RcppT_ase_theta_BFGS`, lg_theta, ni, ni0, pis, lbc, max_iter, eps, show)
}

RcppT_ase_KEG_BFGS <- function(para0, H0, z_AS, RHO_AS, ni0, ni, log_theta, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_RcppT_ase_KEG_BFGS`, para0, H0, z_AS, RHO_AS, ni0, ni, log_theta, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_ase_sfit <- function(H0, para0, z_AS, RHO_AS, ni0, ni, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_ase_sfit`, H0, para0, z_AS, RHO_AS, ni0, ni, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_ase <- function(z_AS, RHO_AS, ni0, ni, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_ase`, z_AS, RHO_AS, ni0, ni, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_TReCASE_LL_KEG <- function(para, H0, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu) {
    .Call(`_asSeq2_RcppT_TReCASE_LL_KEG`, para, H0, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu)
}

RcppT_TReCASE_LL <- function(y, phi, lgy1, mu, ni0, ni, log_theta, pis, lbc) {
    .Call(`_asSeq2_RcppT_TReCASE_LL`, y, phi, lgy1, mu, ni0, ni, log_theta, pis, lbc)
}

RcppT_TReCASE_grad_KEG <- function(para, H0, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu) {
    .Call(`_asSeq2_RcppT_TReCASE_grad_KEG`, para, H0, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu)
}

RcppT_trecase_KEG_BFGS <- function(para0, H0, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_RcppT_trecase_KEG_BFGS`, para0, H0, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_trecase_sfit <- function(H0, para0, y, z, z_AS, RHO, RHO_AS, X, tau1, tau2, lgy1, ni0, ni, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_trecase_sfit`, H0, para0, y, z, z_AS, RHO, RHO_AS, X, tau1, tau2, lgy1, ni0, ni, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_trecase <- function(y, z, z_AS, RHO, RHO_AS, X, tau1, tau2, lgy1, ni0, ni, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_trecase`, y, z, z_AS, RHO, RHO_AS, X, tau1, tau2, lgy1, ni0, ni, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_TReC_ASE_LL_KEG <- function(KEG_EaseGase, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu) {
    .Call(`_asSeq2_RcppT_TReC_ASE_LL_KEG`, KEG_EaseGase, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu)
}

RcppT_TReC_ASE_grad_KEG <- function(KEG_EaseGase, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu) {
    .Call(`_asSeq2_RcppT_TReC_ASE_grad_KEG`, KEG_EaseGase, y, z, z_AS, phi, RHO, RHO_AS, tau1, tau2, ni0, ni, log_theta, tauB, tau, lgy1, expXbeta, lbc, offsets, pis, mu)
}

RcppT_trec_ase_KEG_BFGS <- function(para0, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    .Call(`_asSeq2_RcppT_trec_ase_KEG_BFGS`, para0, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_trec_ase <- function(para0, y, z, z_AS, RHO, RHO_AS, X, tau1, tau2, lgy1, ni0, ni, tauB, tau, lbc, max_iter = 4e3L, eps = 1e-7, show = FALSE) {
    .Call(`_asSeq2_RcppT_trec_ase`, para0, y, z, z_AS, RHO, RHO_AS, X, tau1, tau2, lgy1, ni0, ni, tauB, tau, lbc, max_iter, eps, show)
}

RcppT_CisTrans_ScoreObs <- function(para, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc) {
    .Call(`_asSeq2_RcppT_CisTrans_ScoreObs`, para, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc)
}

RcppT_ASE_ExpFunc <- function(ni, pis_i, vtheta, Expvec) {
    invisible(.Call(`_asSeq2_RcppT_ASE_ExpFunc`, ni, pis_i, vtheta, Expvec))
}

RcppT_CisTrans_Score <- function(para, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc) {
    .Call(`_asSeq2_RcppT_CisTrans_Score`, para, y, z, z_AS, RHO, RHO_AS, X, BETA, phi, tau1, tau2, lgy1, ni0, ni, log_theta, tauB, tau, lbc)
}

RcppT_trecase_mtest <- function(Y, Y1, Y2, Z, XX, RHO, CNV1, CNV2, SNP_pos, sChr, gene_start, gene_end, gChr, GeneSnpList, file_trec = "trecT.txt", file_trecase = "trecaseT.txt", useLRT = FALSE, transTestP = 0.01, cis_window = 1e5, useASE = 1L, min_ASE_total = 8L, min_nASE = 5L, min_nASE_het = 5L, eps = 1e-5, max_iter = 4000L, show = FALSE) {
    invisible(.Call(`_asSeq2_RcppT_trecase_mtest`, Y, Y1, Y2, Z, XX, RHO, CNV1, CNV2, SNP_pos, sChr, gene_start, gene_end, gChr, GeneSnpList, file_trec, file_trecase, useLRT, transTestP, cis_window, useASE, min_ASE_total, min_nASE, min_nASE_het, eps, max_iter, show))
}

